steps:
- id: read-gpg-key-from-secrets
  name: gcr.io/cloud-builders/gcloud
  volumes:
    - name: gnupg
      path: /gnupg  
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=gpg-private-key > /gnupg/gpg-private.key' ]
# 
- id: import-gpg-key
  name: dylanmei/blackbox
  volumes:
  - name: gnupg
    path: /gnupg
  args: [ 'gpg', '--allow-secret-key-import', '--import', '/gnupg/gpg-private.key' ]
- id: decrypt-secrets
  name: dylanmei/blackbox
  volumes:
  - name: gnupg
    path: /gnupg
  env:
  - BLACKBOX_REPOBASE=/workspace
  args: [ 'blackbox_decrypt_all_files' ]
- id: test  
  name: 'docker/compose:1.17.1'
  args:
    - '-f'
    - 'docker-compose.cloud-test.yaml'
    - 'up'
    - '--build'
    - '--exit-code-from'
    - 'test'
- id: build
  name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - '-t'
  - 'gcr.io/augmented-world-276110/twitter-clone-backend'
  - .
- id: push
  name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - 'gcr.io/augmented-world-276110/twitter-clone-backend'
timeout: 1200s
