version: '3'

services: 
    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        command: ['npm', 'test']
    db:
        image: postgres:11
        environment:
            POSTGRES_DB: twitter_clone_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234

